const sayYes = `
Hi there...

So... we both know how much you want this... both know how much you want what's coming. 

We know how much you want to relax... to let go... to read my words and let them do the thinking for you...

To read my words and let them help you feel so good for me.

And I want to give you that.

I want to help you get there.

Let's start with something simple.

The idea of trance can feel so lovely and magical and captivating... 

Just thinking about the word... lingering on the word... 

Trance...

It can bring up so many different kinds of feelings.

So many different ideas and feelings and sensations and desires...

Trance... just linger on the word... feel it in your mind... feel its shape... the way it fits... the way it feels inside you.

Trance... 

Say it out loud now... notice how it feels... in your mouth... on your lips... the way your tongue forms it.

Trance... 

and linger with it just a little while longer... noticing not just the feeling of the word... but also how saying the word makes you feel.

Trance...

And that was easy... wasn't it? 

It's nice... to have something easy to do for me. Because that's how you want trance to feel...

Nice... and... easy...

And now moving from your mind to your body... you can notice the way that your body is... 

passive... 

waiting... 

just still and reading and waiting for my words...

And it's interesting... isn't it? 

How when I write that... you do find yourself focusing on your body... 

Focusing your attention on any shifts and movements... or any stillnesses... just because of the words I used...

The words I used to guide your attention.

And now you're focusing inward again... 

Focusing on your attention... your mind... the way it flits from idea to idea... from inside to outside... from body to mind and back...

And there's something almost disorienting about this shift... when you focus on it... 

Isn't there? 

Because focusing inward... on your mind... on your attention... on your focus... feels a certain way.

And then focusing outward... on your body... on your movements... your stillnesses...

Focusing on the way your body moves... your hands rest... the way you're breathing... that feels a different way... doesn't it?

And it happened again... didn't it? Your focus shifting back and forth... 

mind... 

to body... 

to mind... 

to body...

And when you focus on your mind... you might notice that it feels a little bit different... 

Your focus... your thoughts... the way your mind is moving. 

It's hard to find the right words to describe the feeling...

Fuzzy...

Slow...

Foggy...

Soft...

Easy...

And you're probably not sure about any of these words... each of them is trying to get at some aspect of the feeling... 

But it's OK if they don't seem exactly right... or if you don't feel exactly certain...

But your mind does sort of want to linger on them a little bit... doesn't it? 

Try them out... focus on their shape... how they feel... 

Maybe it will help to say them out loud... to feel them in your mouth... on your lips... 

Just lingering on the sensations... as you try the words out one more time...

Fuzzy...

Slow...

Foggy...

Soft...

Easy...

And while you were focusing on the words and on your mind... something was happening in your body... wasn't it? 

And again your mind sort of wants to find the right words but it's hard to find them... isn't it? 

It's hard to find them when your mind feels like this... when your mind feels so fuzzy...

Slow...

Foggy...

Soft...

Easy...

But I know you're looking for them... and so you try some out... feeling how they fit 

Speaking them and feeling how they feel inside your mind... how they feel on your lips and tongue...

Warm...

Slow...

Heavy...

Soft...

Easy...

And as you focus on these words... try them out... see how they feel... 

Your body might shift or squirm or move a little bit... it might relax and let go of tension... or... it might just feel perfectly still.

And all of these responses are perfect... because it's just your body doing what it wants... 

Easily and automatically... without your mind needing to guide or direct it. 

Your body is just playing along... following along... saying 'yes' for me in all of its own little ways... and that just makes you feel so...

Warm...

Slow...

Heavy...

Soft...

Easy...

Doesn't it?

And your mind is feeling a little bit disoriented from the way your focus keeps moving... back and forth... 

Body... 

to mind... 

to body... 

to mind... 

back and forth. 

And it's a little bit disorienting... a little bit confusing... when you try to think about it... 

But it's also easy to just let it happen... when you let your body and mind say 'yes' like this.

Go ahead... say it for me...

'Yes...'

And as you're reading... you might start to notice how easy it is... 

How easy it is to just let go of the need to do anything at all... and instead... just follow along with what feels good.

And right now... when you feel like this... it feels so good to say 'yes' for me... doesn't it?

You see... hypnosis isn't about doing something... it's more about allowing something... allowing yourself to just... 

Feel... 

Feel that gentle... subtle shift... like how you're already starting to settle into a nice... relaxed rhythm.

And as you read... you might find yourself thinking... 'Am I already feeling it?'  'Am I letting go?' and that's okay... 

It make sense to wonder... to be curious about something you want so very much... doesn't it?

And... of course... 'am I letting go' is so very close... slips so easily... into 'I am letting go'.

Are you letting go?

Yes

That's right. Very good... you are letting go...

You... are... letting... go...

You... are... letting... go...

Why don't you try those words out... see how they feel inside you... see how they make you feel...

I am letting go

That's perfect... and maybe you might find that they make you feel...

Fuzzy... Warm... Slow... Soft... Foggy... Heavy... Easy...

So easy to just... follow along...

Like you're being guided by something deep inside... something that already knows how to respond.

And... as you think about how easy it's becoming... you find yourself saying yes.

'Yes' to this experience... 

'Yes' to feeling good... 

'Yes' to letting go.

Your body is saying it... your mind is saying it... and your voice can say it for me right now...

It's easy to say 'yes' ... isn't it?

There's something... automatic... about it... something that feels so good... so natural.

And the more you say it... the easier it gets...

Like a little loop that just keeps bringing you deeper and deeper... 

Deeper and deeper into this nice... comfortable... relaxed state. 

And you can just enjoy saying 'yes' to whatever I tell you.

Just saying 'yes' for me easily and automatically... without really thinking too hard about what you're saying 'yes' to. 

It's such a lovely idea... isn't it?

And saying yes makes you feel so good... makes you feel so...

Fuzzy... 

Warm... 

Slow... 

Soft... 

Foggy... 

Heavy... 

Easy...

And it all feels so incredibly good right now. Reading... focusing... my words inside of you... saying 'yes' for me...

And you'd say 'yes' to anything right now... wouldn't you?

You'd say 'yes' ... to anything I told you.. because saying 'yes' makes you feel so...

Fuzzy... Warm... Slow... Soft... Foggy... Heavy... Easy...

And this makes it so easy to say 'yes' for me without thinking or worrying... doesn't it?

So easy to say 'yes' for me... and so hard to imagine wanting to do anything else... isn't that right?

And as you say 'yes' for me... you might find that your voice sounds different... 

more distant... 

softer... 

slower... 

and it feels so nice to notice that... doesn't it?

And as you keep reading... you might find that your words feel different... 

the thoughts that make your words feel different... further away... sort of...

Fuzzy... 

Warm... 

Slow... 

Soft... 

Foggy... 

Heavy... 

Easy...

And maybe your breathing starts to slow down now... as I draw your attention to it... everything can just start slowing down... 

Your body slowing down... 

Your mind slowing down... 

Your thoughts slowing down... 

Everyhing feeling so soft... so easy... so relaxing as you let go...

And as your thoughts slow down... nothing else really matters... all you want to do is say 'yes' for me... and it makes you feel so...

Fuzzy... Warm... Slow... Soft... Foggy... Heavy... Easy...

And so now that you're just saying 'yes' for me... and letting the word fill you... fill your mind... 

now that you feel so good that you can't do anything else... I'm going to ask you some questions 

I'm going to ask you some questions and you're just going to answer them... like a helpless little yes-machine... aren't you?

Does it feel good to say 'yes' for me?

Yes

Does it feel automatic to say 'yes' for me?

Yes

Are you hypnotized right now?

Yes

Do you love being hypnotized for me?

Yes

Do you want to sink deeper?

Yes

Do you want to sink deeper for me?

Yes

Do you want to sink deeper into trance for me?

Yes

Do you want me to take you deeper?

Yes

Mmm... very good... such a good little yes-machine.

Yes

And you can find... somehow... without knowing exactly how... without needing to know exactly how... 

without needing to think or worry...

You can find that you just... sink... deeper for me...

Right

Now.

...

Are you hypnotized right now?

Yes

Very good.

...

Perfectly deep... perfectly hypnotized... feeling so very good for me... feeling so very...

Fuzzy...

Warm...

Slow...

Soft...

Foggy...

Heavy...

Easy...

And each time you say 'yes' for me... you just feel better and better... don't you?

And each time you say 'yes' for me... you just sink deeper and deeper... don't you?

That's right. You're doing so well... doing so well for me... being so good for me... sinking so easily for me... and that makes you feel so good... doesn't it?

You're doing so well for me... being so good for me... and that makes you feel so good... happy... giddy... dreamy... proud... doesn't it?

And when you're feeling this good... this deep... this easy... it's so easy just to let me guide you... let me direct you... let me... 

Control you... 

isn't it?

And that's really what you want—you want me to control you... don't you?

You want me to... control you... and it's so easy when you feel like this... when you feel so

Fuzzy... Warm... Slow... Soft... Foggy... Heavy... Easy...

It's so easy to control you when you can't resist... when you feel so helpless... when you can't stop saying 'yes' for me... isn't it?

And each time you say 'yes' for me... you just let a little bit more of that control... of my control... slip inside you... don't you?

Each time you say 'yes' for me... you feel it... more and more... deeper and deeper...

My words... slipping inside...

My control... filling you...

This trance... growing and growing...

My words... taking you... so... deep...

My words... filling your mind... completely... filled

Filled

with trance...

Filled

by my words...

Filled

by my control...

And there's nothing you can do to stop it... nothing you can do to resist it. 

You... are... completely controlled... 

completely 

entranced... 

completely 

hypnotized... 

completely... 

helpless.

Mmm... and that's another delicious little word... isn't it? Say it for me...

Helpless

Feel how good it feels on your lips... filling your mouth... filling your mind... 

helpless...

And that's what you are... my helpless little yes-machine 

and you'll do anything I tell you right now without even thinking about it... won't you?

Helpless... controlled... filled... so deep...

Feeling my control so deep inside of you...

Feeling my words... so deep... inside of you...

Completely... overwhelmingly... desperately... filled...

Filled... with pleasure...

Filled... with trance...

Filled... with control...

Filled... with surrender...


That's right. So good. So good for me. Perfectly still. Perfectly quiet. Perfectly... controlled.

Just waiting for my words to take you deeper. Waiting for my words to fill you. 

Waiting and wanting and so perfectly... helplessly obedient for me like the helpless little yes-machine you are. 

Isn't that right?

That's right.

You're doing so well for me... being so good for me...

And now... it's time to slowly come back... to slowly bring yourself back to the surface... to wake up... 

Feeling and holding onto any aspects of this experience that you want to hold on to.

Or you can just... let it all go and wake up feeling just however you want to feel... 

Just slowly... easily coming back into yourself and letting your thoughts come back... letting your mind come back... letting your body come back

And... with every breath you take... you can feel yourself becoming more aware... more awake... more alert... and you can just slowly... easily start to settle back into the world...

And so... slowly... easily... evenly... at your own pace... waking up for me... coming back out of trance... and back into yourself. That's right. Very good.

And as I count from 1 to 5... you can feel yourself waking up... more and more... with each number...

1...

2...

3...

4...

5...

Welcome back.`

export default sayYes;